name: hw2_env

dependencies:
  - python=3.7
  - pytorch-gpu=1.3.1
  - torchvision
  - pip
  - pip:
      - gdown
      - numpy
      - pandas
      - wandb
      - sklearn
      - seaborn
      - opencv-python
      - pytorch==1.3.1
      - torchvision==0.4.2
      - matplotlib==3.4.2
