name: hw2_env

dependencies:
  - python=3.7
  - pytorch=1.3.1
  - pytorch-gpu=1.3.1
  - torchvision=0.4.2
  - pip
  - pip:
      - gdown
      - numpy
      - pandas
      - wandb
      - sklearn
      - seaborn
      - scipy
      - opencv-python
      - matplotlib
